### PR TITLE
Relative path fix. Does not work in every browser.

### PR DESCRIPTION
**Pull request by Antoshjkee**
Works in Edge but does not in Chrome. 404 error was thrown trying launch. Removing "~" fixed the problem.

### CODE REVIEW

**Comment by dawoe** [comment]
Hi @Antoshjkee 

Are you perhalps using Chrome 66. There is a know bug in Umbraco in Chrome.

Have a look at his issue : https://github.com/dawoe/umbraco-tour-editor/issues/17

Dave

**Comment by Antoshjkee** [comment]
Oh, Great. Should off looked at this in the first place. Thank you.

**Comment by dawoe** [comment]
I think that will be the cause. I alsof think your fix will break the package when umbraco is used in a virtual directory

**Comment by Antoshjkee** [comment]
Good to know this. Thank you, Dave.

**Pull request closed without merging**
